### ISSUE TITLE
What is your motivation for moving from Sublime to Vim?

### ISSUE THREAD

**Issue by lencioni** [woliveiras/ama#3]
I noticed in https://github.com/woliveiras/ama/issues/2#issuecomment-213941950 you mentioned that you are migrating to Vim. I'm just curious why?

**Comment by woliveiras** [comment]
At first it was just curiosity, but I ended up liking of VIM.

Use a text editor direct of terminal is cool too.

Sublimetext have all of VIM have, i guess. But, VIM is free, and more faster than Sublime.

At first I did not think true, but the VIM shortcuts, dynamicity and modes really make us more agile as well. Little thing, but make.

I think I fell in love it was the .vimrc! kkkkkk

**Comment by woliveiras** [comment]
I have a little book that I was making notes of what I learned about the VIM (in PT-BR):

http://woliveiras.com.br/vimparanoobs/

**Comment by lencioni** [comment]
Cool! I switched from Sublime to Vim about 4 years ago too. If you haven't yet, you should check out [tmux](https://tmux.github.io/)--it goes great with terminal Vim.

**Comment by woliveiras** [comment]
Wow! Great!

I will look Tmux, is already in my To do list! 😄 

I looked your dotfiles and take your .vimrc and tmux.conf to study! kkkk

**Comment by gtcarlos-sage** [comment]
Worth taking a look at [tmuxinator](https://github.com/tmuxinator/tmuxinator) to manage tmux sessions
