### ISSUE TITLE
Você pretende em um futuro próximo morar fora do Brasil?

### ISSUE THREAD

**Issue by rafaels88** [woliveiras/ama#5]
Sendo sim ou não, quais as motivações para ir ou ficar?

**Comment by woliveiras** [comment]
Rapaz, até hoje eu só venho vivendo em uma incógnita quanto a isso! HAHAHA

Se alguma empresa bem legal me chamar pra ir pra um país que compactua com minhas visões políticas, tenha um clima legal e feijoada, até posso pensar em ir. Mas até hoje eu só passei por um momento de querer sair do país e era por querer desafios técnicos de verdade, o que não estava encontrando no Brasil por procurar errado mesmo. Hoje eu achei esse desafio, então fica difícil eu querer sair do país só por querer mesmo.

Como eu nunca viajei pra fora, não consigo ter um parâmetro de comparação com o nosso país - só acreditar no que os outros falam é perigoso, visto que temos nosso próprio perfil e pode acabar sendo uma experiência boa pra outra pessoa e ruim pra gente - daí fica difícil eu querer ir morar fora.

É algo que eu "não pretendo" se for pensar em eu estar me preparando pra isso. Não estou. Mas se aparecer uma oportunidade legal, daí eu pico o pé! 😂 

Já apareceram excelentes oportunidades (com os requisitos que falei acima) e eu perdi por causa do inglês, então, ano que vem, meu foco é melhorar no idioma pra estar sim pronto se um dia eu inventar de sair daqui, sabe?
