### ISSUE TITLE
Qual seu trabalho dos sonhos, atualmente?

### ISSUE THREAD

**Issue by rafaels88** [woliveiras/ama#6]
Claro que isso pode mudar de um dia pro outro. Mas qual seu tipo de trabalho ideal no qual você poderia focar full time nele e ganhar um salário pra não precisar fazer um trabalho paralelo como sustento?

**Comment by woliveiras** [comment]
Fala, @rafaels88!

Me desculpe pela demora em responder.

Cara, hoje eu já trabalho no meu emprego dos sonhos: trabalho como programador e já passei por algumas empresas maneiras e estou em uma empresa legal.

O salário de uma pessoa dev, em SP, é bem alto (na minha opinião) e, apesar do custo de vida aqui também ser mais alto, me garante um sustento para pagar aluguel, investir, ajudar pessoas em forma de doações mensais e ainda gastar uma grana com coisas que eu curto, como esporte (patins, skate), games ou sair pra um rolê maneiro.

Acho que hoje minha vida está em um momento bem legal. 🙏 

Para quem já foi desde ajudante de mestre de obras (servente de pedreiro), ajudante geral em várias empresas, atendente de call center e várias outras profissões que não pagam tão bem (assim como as empresas e a própria sociedade não valorizam) até aviãozinho na boca de fumo, hoje estou no topo dos meus sonhos e o que vier além disso é puro lucro. 🤘 

Até por isso que eu foco tanto em trazer pessoas de baixa renda pra essa área. É algo que abre portas e quebra várias barreiras pra gente.
